service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  profile: matt.miller
  region: us-east-2
  environment:
    test_env_var: "something"
    TH_CONFIRM_PASS: ${file(./config.js):TH_CONFIRM_PASS}
    TH_CONFIRM_USER: ${file(./config.js):TH_CONFIRM_USER}

functions:
  auth-register:
    handler: lambda-handler-auth.register
    events:
      - http:
          method: post
          path: auth/register

  auth-testEnv:
    handler: lambda-handler-auth.testEnv
    events:
      - http:
          method: post
          path: auth/testEnv
